
#gamma
g1=$(awk -F "" '{print $1}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g2=$(awk -F "" '{print $2}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g3=$(awk -F "" '{print $3}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g4=$(awk -F "" '{print $4}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g5=$(awk -F "" '{print $5}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g6=$(awk -F "" '{print $6}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g7=$(awk -F "" '{print $7}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g8=$(awk -F "" '{print $8}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g9=$(awk -F "" '{print $9}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g10=$(awk -F "" '{print $10}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g11=$(awk -F "" '{print $11}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g12=$(awk -F "" '{print $12}' input.txt | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
g=$(echo $((2#"$g1$g2$g3$g4$g5$g6$g7$g8$g9$g10$g11$g12")))
#epsilon
e1=$(awk -F "" '{print $1}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e2=$(awk -F "" '{print $2}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e3=$(awk -F "" '{print $3}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e4=$(awk -F "" '{print $4}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e5=$(awk -F "" '{print $5}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e6=$(awk -F "" '{print $6}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e7=$(awk -F "" '{print $7}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e8=$(awk -F "" '{print $8}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e9=$(awk -F "" '{print $9}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e10r=$(awk -F "" '{print $10}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e11r=$(awk -F "" '{print $11}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e12r=$(awk -F "" '{print $12}' input.txt | sort | uniq -c | sort -n | awk 'NR==1{print $2}')
e=$(echo $((2#"$e1$e2$e3$e4$e5$e6$e7$e8$e9$e10r$e11r$e12r")))
a=$(( g*e ))
echo $a 